Feature/homework 1
VtulkinVladimir/FocusStartHomeworks pull request #1
Opened 2021-10-29 18:43 UTC by VtulkinVladimir

Разработал консольное приложение. Реализована возможность добавлять автомобили, распечатывать информацию о всех автомобилях, или только об определенных

2021-11-02 15:12 UTC, AlexRaptor requested changes
Поправь замечания в коментах

2021-11-02 15:12 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +	let year = Int(strongReadLine("Введите год выпуска"))
- [ ] год выпуска не обязательное поле, не нужно его строгом просить

2021-11-02 15:12 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +	let number = strongReadLine("Введите гос. номер автомобиля")
- [ ] и это поле не обязательно

2021-11-02 15:12 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +	0) Выход
зачем при вводе типа кузова есть пункт выход, и почему его тогда нету в запросах других данных?

2021-11-02 15:12 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +	case "1": return .sedan
- [x] выглядит так, что просто в Body нужно добавить инициализатор по порядковому номеру

2021-11-02 15:13 UTC, AlexRaptor commented
И добавь в README в ветке ФИО

2021-11-03 18:47 UTC, VtulkinVladimir commented on homework-1/homework-1/main.swift
> +	let year = Int(strongReadLine("Введите год выпуска"))
по поводу этого есть вопрос, у меня ведь это поле опциональное, и получается что если у него не получится скастить строчку к инту то он передаст в инициализатор машинки nil. Нужно ли писать отдельную функцию

2021-11-03 18:49 UTC, VtulkinVladimir commented on homework-1/homework-1/main.swift
> +	let year = Int(strongReadLine("Введите год выпуска"))
отмена вопроса. я в стронгРидЛайне не проверял строчку на пустоту, а действие полезное. сейчас уже очевидно что другая функция нужна))

2021-11-04 02:46 UTC, AlexRaptor requested changes

2021-11-04 02:46 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +	1) Седан
У тебя есть enum Body, который типизирован стрингом, и значениям которого можно итерироваться. Собери список типов кузова из него, не нужно хардкодить.

2021-11-04 02:46 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +func sorting() {
это не сортировка, а фильтрация

2021-11-04 02:46 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +func sort(body: Body) {
и здесь не сортировка

2021-11-04 02:46 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +	for car in cars {
не нужно в цикле, используй конвейер filter{...}.forEach{...}

2021-11-05 06:54 UTC, AlexRaptor requested changes

2021-11-05 06:54 UTC, AlexRaptor commented on homework-1/homework-1/main.swift
> +		cars.forEach { car in
нет, не так... я даже прямо написал в прошлом комментарии, как нужно сделать

> не нужно в цикле, используй конвейер filter{...}.forEach{...}

Смотри, какая тут получается у тебя логика: ты перебираешь все авто и если у текущего авто нужный тип кузова, то ты его распечатываешь.
Это имеет право на жизнь, но я хочу, что бы ты понял, как использовать конвейеры...

- [ ] Нужно, что бы ты реализовал следующую логику: сперва отфильтруй авто, получив список только с нужным типом кузова, а потом уже для каждого выведи его на экран

2021-11-06 05:54 UTC, AlexRaptor approved these changes

2021-11-06 05:54 UTC, AlexRaptor commented on homework-1/homework-1/Car.swift
> +	case sedan
- [ ] добавь тут строковые значения на русском языке

2021-11-06 16:24 UTC, merged