Feature/homework 3
VtulkinVladimir/FocusStartHomeworks pull request #3
Opened 2021-11-14 12:40 UTC by VtulkinVladimir

Приложение - визитка

2021-11-15 09:39 UTC, c0dedbear requested changes
Фотка огонь)

Ошибки - те про которые писал в телеге, final'ы, магические цифры.
Так же есть баг в альбомной ориентации на первом экране - часть текста не видно.
Ну и tabBar без иконок совсем уж печально выглядит.

2021-11-15 09:39 UTC, c0dedbear commented on MyCV/MyCV/Hobbys/Hobbys.swift
> +class MyHobbys
Почему класс, а не структура?

2021-11-15 09:41 UTC, c0dedbear commented on MyCV/MyCV/Hobbys/HobbysViewController.swift
> +		self.view = HobbysView()
viewDidLoad не то место где нужно менять корневую вью. Это нужно делать в loadVIew.

2021-11-15 09:41 UTC, c0dedbear commented on MyCV/MyCV/MainTabBar.swift
> +		let skillsVc = SkillsViewController(nibName: nil, bundle: nil)
Нет смысла задавать такие иниты . Можно просто InfoViewController()  и т.д.

2021-11-16 17:22 UTC, VtulkinVladimir commented on MyCV/MyCV/Hobbys/Hobbys.swift
> +class MyHobbys
честно говоря как-то не задумывался даже, делал как делал до этого. ну наверное чтобы не копировался каждый раз когда используется. Хотя в моем случае он используется один раз, и меняться там ничего не запланировано тогда смысла от класса получается и нет

2021-11-16 17:24 UTC, VtulkinVladimir commented
не могу найти как ответить на коментарий насчет бага по первому экрану. дело в том, что там вообще не планировалась альбомная ориентация, поэтому я даже и не проверял как смотрится при ней. видимо забыл её отключить. или надо сделать чтоб и в альбомной работало?

2021-11-17 07:06 UTC, c0dedbear commented on MyCV/MyCV/Hobbys/Hobbys.swift
> +class MyHobbys
Всегда когда возможно лучше использовать value type.

2021-11-17 07:08 UTC, c0dedbear approved these changes
Принято

2021-11-17 07:08 UTC, merged